.PHONY: all clean cleanall


all:
	$(MAKE) -C tinyPTC
	$(MAKE) -C picoPNG

clear:
	$(MAKE) -C tinyPTC all
	$(MAKE) -C picoPNG clean
clearall:
	$(MAKE) -C tinyPTC cleanall
	$(MAKE) -C picoPNG cleanall
